apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-web-ns
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: todo-app
  type: ClusterIP
